#!/usr/bin/env python3
"""Phase-4 indexer: roll bugs/*.json up into catalog.json (machine) + INDEX.md
(human). Per-tool / per-label / per-repo / per-state rollups, umbrella impact
chains, a by-year timeline, and the 3-unit reconciliation. Read-only over bugs/.

Run last: classify.py -> group.py -> enrich.py -> index.py.
"""
import json, os, glob, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUGS = os.path.join(ROOT, "bugs")
SRC = os.path.join(ROOT, "sources")


def year_of(b):
    for a in b.get("raw", []):
        try:
            d = json.load(open(os.path.join(ROOT, a)))
            ca = d.get("created_at")
            if ca:
                return ca[:4]
        except Exception:
            pass
    return None


def main():
    allbugs = [json.load(open(f)) for f in sorted(glob.glob(os.path.join(BUGS, "*.json")))]
    umbrellas = [b for b in allbugs if b["is_umbrella"]]
    bugs = [b for b in allbugs if not b["is_umbrella"]]

    def rollup(bs):
        issues = set(a for b in bs for a in b["issues"])
        prs = set(a for b in bs for a in b["prs"])
        shared = set(a for b in bs for a in b.get("shared_fix_prs", []))
        related = set(a for b in bs for a in b.get("related_prs", []))
        return {
            "bugs": len(bs),
            "issues": len(issues),
            "fix_prs": sum(b.get("n_fix_prs", 0) for b in bs),
            "backports": sum(b.get("n_backports", 0) for b in bs),
            "shared_fixes": len(shared),
            "related_prs": len(related),
            "pr_artifacts": len(prs | shared),
            "synthetic": sum(1 for b in bs if b.get("is_synthetic")),
        }

    by_tool = {t: rollup([b for b in bugs if b["tool"] == t])
               for t in sorted(set(b["tool"] for b in bugs))}
    by_repo = collections.Counter(b["target_repo"] for b in bugs)
    by_state = collections.Counter(b["status"] for b in bugs)
    by_filed = collections.Counter(b["filed_by"] for b in bugs)
    by_label = collections.Counter(l for b in bugs for l in b["labels"])
    by_year = collections.Counter(y for b in bugs if (y := year_of(b)))
    # exclude bots + the bpo migration-bot UUID from the "collaborators" metric
    import re as _re
    BOTS = {"miss-islington", "bedevere-bot", "cpython-cla-bot", "github-actions"}
    _uuid = _re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-", _re.I)
    filers = collections.Counter(x for b in bugs for x in b.get("filers", [])
                                 if x not in BOTS and not x.endswith("[bot]")
                                 and not _uuid.match(x))

    # campaign findings (authoritative, from milestones — see FINDINGS.md)
    campaign = json.load(open(os.path.join(SRC, "findings_rollup.json"))).get("campaign_findings", {})

    # umbrella impact chains
    chains = []
    for u in umbrellas:
        chains.append({"umbrella": (u["issues"] or u["prs"] or [u["bug_id"]])[0],
                       "title": u["title"], "tool": u["tool"]})

    totals = {
        "bug_records": len(allbugs), "bugs": len(bugs), "umbrellas": len(umbrellas),
        "synthetic_bugs": sum(1 for b in bugs if b.get("is_synthetic")),
        "issue_artifacts": len(set(a for b in bugs for a in b["issues"])),
        "pr_artifacts": len(set(a for b in bugs for a in b["prs"])),
        "distinct_fixes": sum(b.get("n_fix_prs", 0) for b in bugs),
        "backports": sum(b.get("n_backports", 0) for b in bugs),
        "external_repos": len(by_repo),
    }

    catalog = {
        "generated_note": "run tools/index.py to regenerate",
        "totals": totals, "by_tool": by_tool, "by_repo": dict(by_repo.most_common()),
        "by_state": dict(by_state), "by_filed_by": dict(by_filed),
        "by_label": dict(by_label.most_common()), "by_year": dict(sorted(by_year.items())),
        "top_filers": dict(filers.most_common(20)),
        "umbrella_chains": chains, "campaign_findings": campaign,
    }
    json.dump(catalog, open(os.path.join(ROOT, "catalog.json"), "w"), indent=1)

    # ---- INDEX.md ----
    L = []
    L.append("# Catalog index\n")
    L.append("*Generated by `tools/index.py` from `bugs/*.json`. Counts are "
             "**bugs** (deduped) and **artifacts** (issues/PRs); campaign "
             "**findings** are a separate, larger unit — see `FINDINGS.md`.*\n")
    L.append("## Totals\n")
    L.append(f"- **{totals['bugs']} bugs** across **{totals['external_repos']} external projects** "
             f"({totals['synthetic_bugs']} catalog-only w/o a GitHub artifact; "
             f"{totals['umbrellas']} umbrella containers excluded)")
    L.append(f"- **{totals['issue_artifacts']} issue-artifacts + {totals['pr_artifacts']} PR-artifacts** "
             f"({totals['distinct_fixes']} distinct fixes + {totals['backports']} backports)\n")

    L.append("## By tool\n")
    L.append("| tool | bugs | issues | PR-artifacts | fixes | backports | synthetic |")
    L.append("|---|---|---|---|---|---|---|")
    for t, r in sorted(by_tool.items(), key=lambda x: -x[1]["bugs"]):
        L.append(f"| {t} | {r['bugs']} | {r['issues']} | {r['pr_artifacts']} | "
                 f"{r['fix_prs']} | {r['backports']} | {r['synthetic']} |")

    L.append("\n## By filed-by (collaboration)\n")
    for k, v in by_filed.most_common():
        note = {"self+maintainer": " — you filed the issue, a maintainer authored the fix",
                "maintainer": " — filed entirely by others from your reports/gists",
                "self": " — filed by you", "none": " — gisted/drafted, not filed",
                "self+commit": " — you reported, fixed directly in a commit"}.get(k, "")
        L.append(f"- **{k}: {v}**{note}")
    L.append(f"\nTop external filers of our findings: " +
             ", ".join(f"{a} ({n})" for a, n in filers.most_common(10)))

    L.append("\n## By state\n")
    for k, v in by_state.most_common():
        L.append(f"- {k}: {v}")

    L.append("\n## By label (top 20 — sliceable, e.g. crashes)\n")
    for l, n in by_label.most_common(20):
        L.append(f"- `{l}`: {n}")

    L.append("\n## By repo (top 20)\n")
    for r, n in by_repo.most_common(20):
        L.append(f"- {r}: {n}")

    L.append("\n## Timeline (bugs by year created)\n")
    for y, n in sorted(by_year.items()):
        L.append(f"- {y}: {n}")

    L.append("\n## Umbrella impact chains\n")
    for c in chains:
        L.append(f"- **{c['umbrella']}** ({c['tool']}) — {c['title'][:80]}")

    L.append("\n## Campaign findings (authoritative — different units, never summed)\n")
    L.append("- **cext-review-toolkit:** ~690 FIX-level findings (215+ reproduced) / 50 exts")
    L.append("- **ft-review-toolkit:** 4,556+ races, 30+ live crashes / 18 exts")
    L.append("- See `FINDINGS.md` for the full 3-unit explanation.\n")

    open(os.path.join(ROOT, "INDEX.md"), "w").write("\n".join(L) + "\n")

    print(f"wrote catalog.json + INDEX.md")
    print(f"bugs={totals['bugs']} issues={totals['issue_artifacts']} "
          f"prs={totals['pr_artifacts']} repos={totals['external_repos']}")
    print("by tool:", {t: r["bugs"] for t, r in sorted(by_tool.items(), key=lambda x: -x[1]['bugs'])})
    print("by year (top):", dict(sorted(by_year.items())))


if __name__ == "__main__":
    main()
